# This is a workflow for publish package via lerna to npm
name: lerna-publish

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --prune
      - name: Use Node.js 12
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: |
          npm i
          npm run lerna:publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
