name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        run: npm i
        env:
          NPM_TOKEN: ${{secrets.NPM_SECRET}}
      - name: Build
        run: |
           npm deploy:tags
           npm deploy:lerna
        env:
          NPM_TOKEN: ${{secrets.NPM_SECRET}}