# This is a workflow for publish package via lerna to npm
name: lerna-publish

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - run: |
        echo //registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN} > .npmrc
        npm i
        npm run lerna:publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_SECRET}}
