name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
          registry-url: 'https://registry.npmjs.org'

      - name: Install packages
        run: sudo yarn --frozen-lockfile
        env:
          NPM_TOKEN: ${{secrets.NPM_SECRET}}
      - name: Build
        run: |
          sudo yarn deploy:tags
          sudo yarn deploy:lerna
          echo "Skipping automated deploy..."
        env:
          NPM_TOKEN: ${{secrets.NPM_SECRET}}